[project]
name = "snakemake-pixi"
version = "1.1.0"
description = "A template for installing and running a snakemake workflow with pixi."
authors = ["Sibbe Bakker <sibbe.l.bakker@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]


[tasks]
jobscript = "mkdir logs/slurm -p; sbatch workflow/scripts/jobscript.sh"
make = "snakemake --use-conda -c 1"
test = "snakemake --use-conda -c 1 -np"
t = "tree -L 3"
help  = "snakemake help -c 1 --quiet all"
update_dag = "snakemake --quiet all -c 1 'results/method.png' && mv results/method.png resources; mv resources/method.png resources/pipeline.png"
slurm = "snakemake --use-conda --workflow-profile workflow/profiles/slurm"


[dependencies]
graphviz = ">=9.0.0,<9.1"
curl = ">=8.7.1,<8.8"
snakemake = ">=8.10.8,<8.11"
mamba = ">=1.5.8,<1.6"
wget = ">=1.21.4,<1.22"
gzip = ">=1.13,<2"
apptainer = ">=1.3.0,<1.4"
snakemake-executor-plugin-slurm = ">=0.6.0,<0.7"
tree = ">=2.1.1,<2.2"
squashfuse = ">=0.5.2,<0.6"
unzip = ">=6.0,<7"
gawk = ">=5.3.0,<5.4"

[system-requirements]
linux="4.18"
