# https://www.embl.org/groups/bioinformatics-rome/blog/2022/04/snakemake-profile-4-defining-resources-and-threads/
# https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html
# cluster: "sbatch --output=\"jobs/{rule}/slurm_%x_%j.out\" --error=\"jobs/{rule}/slurm_%x_%j.log\""
executor: slurm
latency-wait: 60
jobname: "{rule}.{jobid}" 
jobs: 100

default-resources:
  - mem_mb=2000
  - runtime='1440'
  # - tasks=2
  # - mpi="sbatch"
  - disk_mb=5000
set-resources:
  run_neural_plexer:
    mem_mb: 32000
    slurm_extra:  "'--gres=gpu:a100:1'"
    constraint: "gpu"
    tasks: "1"
    cpus_per_task: 10
    mem: "128G"
    slurm_partition: 'gpu1'
    runtime: '1440'
    slurm_account: "mpmp_gpu"
  run_plip:
    mem_mb: 120000
    tasks: "1"
    cpus_per_task: 10
    slurm_partition: 'cpu1'
    runtime: '1440'
    slurm_account: "mpmp_cpu"
